# Generated by Django 4.0.4 on 2022-04-22 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMDB_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year_released',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1800)])),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('runtime', models.IntegerField()),
                ('certificate', models.CharField(max_length=50, null=True)),
                ('plot_summary', models.TextField()),
                ('poster_link', models.URLField()),
                ('gross', models.CharField(max_length=200, null=True)),
                ('artist', models.ManyToManyField(to='movie_store.artist')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_store.director')),
                ('genre', models.ManyToManyField(to='movie_store.genre')),
                ('imdb_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_store.imdb_rating')),
                ('year_released', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_store.year_released')),
            ],
        ),
    ]
