# Generated by Django 4.0.4 on 2022-04-29 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year_released',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(1800)]),
        ),
    ]
