# Generated by Django 4.0.4 on 2022-04-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0002_cart_customer_movies_created_date_movies_price_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year_released',
            options={'ordering': ['year']},
        ),
    ]
